task-10
MashaRakitskaya/PraktikumGameDoodleJump pull request #11
Opened 2022-09-06 20:41 UTC by DmitriyExcl

Добавил верстку страниц по регистрации и логину, надо убрать инлайн стили и переписать всплывашку под emotin

2022-09-07 16:07 UTC, MashaRakitskaya requested changes
Написала комментарии по проекту, обрати пожалуйста на них внимание

2022-09-14 07:47 UTC, AndreyTsvetkov requested changes
немного комментариев + поддерживаю написанное Марией

2022-09-14 07:47 UTC, AndreyTsvetkov commented on src/components/TextField/TextField.tsx
> +const TextField: FC<IPropsInput> = ({
Имхо, TextField лучше название, чем просто Field; Input - норм
В любом случае надо свести к единым для проекта компонентам

2022-09-14 07:47 UTC, AndreyTsvetkov commented on src/contans/constans.tsx
> +export const ENDPOINTS = {
Опечатка в названии директории и файла

2022-09-14 07:47 UTC, AndreyTsvetkov commented on src/pages/Auth/SignIn/SugnIn.tsx
> +const SugnIn = () => {
опечатка

2022-09-14 07:47 UTC, AndreyTsvetkov commented on src/pages/Auth/SignIn/SugnIn.tsx
> +            // Убрать
Есть хорошая практика не оставлять в PR todo-шки

2022-09-14 07:47 UTC, AndreyTsvetkov commented on src/pages/ChangeData/ChangePersonData/ChangetData.tsx
> +import { ReactComponent as UserIcon } from '../../../assest/svg/user-icon.svg';
опечатка в названии assets

2022-09-20 22:39 UTC, AndreyTsvetkov approved these changes

2022-09-21 14:12 UTC, MashaRakitskaya commented on src/components/TextField/text-field.styles.js
> +  font-family: 'Play';
Ок

2022-09-21 14:13 UTC, MashaRakitskaya commented on src/components/TextField/text-field.styles.js
> +  border-bottom: 2px solid;
ок

2022-09-21 14:34 UTC, MashaRakitskaya commented on src/pages/Auth/styles.js
> +import styled from '@emotion/styled';
ок

2022-09-21 14:35 UTC, MashaRakitskaya commented on src/pages/ChangeData/styles.js
> +import styled from '@emotion/styled';
ок

2022-09-21 14:35 UTC, MashaRakitskaya commented on src/pages/Auth/SignUp/SignUp.tsx
> +      <SignInWrapper>
ок

2022-09-27 14:24 UTC, merged