Task 2 popup layout
MashaRakitskaya/PraktikumGameDoodleJump pull request #12
Opened 2022-09-09 13:35 UTC by MashaRakitskaya

2022-09-09 15:16 UTC, KaznacheevDaniil requested changes

2022-09-09 15:16 UTC, KaznacheevDaniil commented on src/components/Popup/Popup.tsx
> +        <Button onClick={() => {}} buttonText={buttonText} type={buttonType} />
Лучше сделать, чтобы кнопку можно было передать как потомка.
Например, нужно будет окно без кнопки, или несколько кнопок сразу. 
Теряется "Масштабируемость")

2022-09-09 15:16 UTC, KaznacheevDaniil commented on src/components/Popup/Popup.tsx
> +  buttonText: string;
Лучше убрать отсюда пропсы для кнопки, чтобы не привязывать кнопку с модалке.

2022-09-09 15:16 UTC, KaznacheevDaniil commented on src/components/Popup/popup.css
> +.popup {
Не совсем пойму, для чего классы вынесены в отдельный файл?

2022-09-14 07:38 UTC, AndreyTsvetkov requested changes

2022-09-14 07:38 UTC, AndreyTsvetkov commented on src/components/Button/Button.styles.ts
> +  width: ${(props: any) => (props.notPriority ? '121px' : '100%')};
почему any?)

2022-09-14 18:15 UTC, MashaRakitskaya commented on src/components/Button/Button.styles.ts
> +  width: ${(props: any) => (props.notPriority ? '121px' : '100%')};
исправила

2022-09-14 18:16 UTC, MashaRakitskaya commented on src/components/Popup/popup.css
> +.popup {
исправлено

2022-09-14 18:16 UTC, MashaRakitskaya commented on src/components/Popup/Popup.tsx
> +  buttonText: string;
исправлено

2022-09-14 18:16 UTC, MashaRakitskaya commented on src/components/Popup/Popup.tsx
> +        <Button onClick={() => {}} buttonText={buttonText} type={buttonType} />
исправлено

2022-09-16 12:52 UTC, AndreyTsvetkov commented on src/components/App/App.tsx
>    function closeByOverlay(event: any): void {
1) функция не стрелка
2) any известно на что заменить

2022-09-16 18:00 UTC, KaznacheevDaniil commented on src/components/Popup/Popup.tsx
> +        <Button onClick={() => {}} buttonText={buttonText} type={buttonType} />
ок

2022-09-16 18:01 UTC, KaznacheevDaniil commented on src/components/Popup/popup.css
> +.popup {
ок

2022-09-20 14:35 UTC, MashaRakitskaya commented on src/components/App/App.tsx
>    function closeByOverlay(event: any): void {
исправила

2022-09-20 22:37 UTC, AndreyTsvetkov approved these changes

2022-09-21 14:41 UTC, merged