Task 17 update main func for game
MashaRakitskaya/PraktikumGameDoodleJump pull request #18
Opened 2022-09-20 17:23 UTC by KaznacheevDaniil

2022-10-10 20:44 UTC, AndreyTsvetkov requested changes
Несколько комментариев

2022-10-10 20:44 UTC, AndreyTsvetkov commented on src/components/GameItem/Bonuses/StackOverflow/StackOverflow.ts
> +
не похоже на законченный функционал, он точно нужен в PR?

2022-10-10 20:44 UTC, AndreyTsvetkov commented on src/components/GameItem/Character/Character.ts
>  class Character {
Нет должен ли по изначальной задумке он реализовывать интерфейс выше?

2022-10-10 20:44 UTC, AndreyTsvetkov commented on src/components/GameItem/Character/Character.ts
> +interface CharacterInterface {
Название этого интерфейса вызывает подозрения о его целесообразности. Вообще мы не должны включать в названии сущности метатип этой сущности. Мы же именуем класс ниже CharacterClass. А тут нам пришлось, из-за того, что иначе имена окажутся одинаковыми. Ну это плохой способ сделать имена разными. Если у этих сущностей реально есть смысловое отличие, то именно из него должно происходить различие имён. Иначе, кажется, что одна из них лишняя. Например, почему бы просто не экспортировать везде класс, зачем вообще нужен этот интерфейс?

2022-10-10 20:44 UTC, AndreyTsvetkov commented on src/components/GameItem/Character/Character.ts
> +    console.log('STOP')
В финальном PR стоит убирать отладочный вывод

2022-10-10 20:44 UTC, AndreyTsvetkov commented on src/components/GameItem/utils/Backgound.ts
> +class Backgound {
опечатка

2022-10-10 20:44 UTC, AndreyTsvetkov commented on src/components/GameItem/utils/FullScreen.ts
> +const activateFullscreen = (element: any) => {
ничем не оправданный any
надо описать тип. либо это просто тип того, что возвращает (document.getElementById('Game')), либо, даже если там не хватает каких-то еще свойств, это он же & { недостающееСвойство?: () => unknown }

2022-11-01 15:18 UTC, MashaRakitskaya commented on src/components/GameItem/GameItem.tsx
> +    if (currentMonster && !currentMonster.isDead) {
много вложенных операторов if , если использовать оператор  [Логическое И (&&) ](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Logical_AND)  код будет проще читать относится к строкам от 199 до 240

2022-11-05 14:53 UTC, AndreyTsvetkov requested changes

2022-11-05 14:53 UTC, AndreyTsvetkov commented on src/components/GameItem/Audio/AudioCustom.ts
> +      // @ts-ignore
Не очень принципиально, но я бы лучше добавил просто проверку на плеер в условие, и этим самым убрал бы необходимость в подсказках компилятору

2022-11-05 14:53 UTC, AndreyTsvetkov commented on src/components/GameItem/Bonuses/Bonuses.ts
> +    let isExpire = false;
нейминг: локальные переменные с маленькоой

2022-11-05 14:53 UTC, AndreyTsvetkov commented on src/components/GameItem/GameItem.styles.js
> +  background: #000000;
+1

2022-11-05 14:53 UTC, AndreyTsvetkov commented on src/components/GameItem/GameItem.tsx
> +    //setIsGameStop(false);
так здесь должно что-то быть?

2022-11-05 14:53 UTC, AndreyTsvetkov commented on src/components/GameItem/GameItem.tsx
> +        width={1600} //500 - пока что произвольная величина
тут следы тех пятиста, но само значение уже другое, все же константа точно нужна

2022-11-16 11:28 UTC, AndreyTsvetkov commented on src/components/GameItem/GameItem.tsx
> +    //setIsGameStop(false);
вопрос вроде остается

2022-11-16 11:28 UTC, AndreyTsvetkov approved these changes

2022-11-16 11:30 UTC, merged