task-12-add api leader board
MashaRakitskaya/PraktikumGameDoodleJump pull request #27
Opened 2022-10-14 07:01 UTC by DmitriyExcl

add api leader board

2022-11-01 11:45 UTC, MashaRakitskaya commented on src/utils/constants.ts
>  export const leaderboardList: LeaderboardListProps[] = [
```
export const leaderboardList: LeaderboardListProps[] = [
  {
    id: '1',
    name: 'Elena List',
    score: 1246434,
    urlImg:
      'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=417&q=80'
  }
];
```
 вроде как нигде не используется можно удалять

2022-11-05 14:42 UTC, AndreyTsvetkov requested changes

2022-11-05 14:42 UTC, AndreyTsvetkov commented on src/models/IGedLeaderBoardParams.tsx
> +export interface IGetLeaderboardParams {
Название файла (опечатка)

2022-11-05 14:42 UTC, AndreyTsvetkov commented on src/models/ILeaderBoardResponse.tsx
> +export interface ILeaderboardItem {
Если лидерборд у нас в одно слово, надо везде выдерживать такое написание, а не делать его в два слова, как например, в названиях файлов тут есть

2022-11-09 20:22 UTC, DmitriyExcl commented on src/utils/constants.ts
>  export const leaderboardList: LeaderboardListProps[] = [
убрал

2022-11-09 20:23 UTC, DmitriyExcl commented on src/models/IGedLeaderBoardParams.tsx
> +export interface IGetLeaderboardParams {
done

2022-11-09 20:24 UTC, DmitriyExcl commented on src/models/ILeaderBoardResponse.tsx
> +export interface ILeaderboardItem {
согласен, не досмотрел

2022-11-09 20:27 UTC, merged