Task 45 api leaderboard for game
MashaRakitskaya/PraktikumGameDoodleJump pull request #57
Opened 2022-11-25 12:10 UTC by KaznacheevDaniil

2022-11-25 17:27 UTC, MashaRakitskaya approved these changes

2022-11-25 17:28 UTC, MashaRakitskaya approved these changes

2022-11-25 17:28 UTC, MashaRakitskaya commented on src/components/LeaderboardItem/LeaderboardItem.tsx
> +      <Avatar alt="avatar" src={urlImg?.[0] === '/' ? 'https://ya-praktikum.tech/api/v2/resources' + urlImg : urlImg}></Avatar>
`    import { ENDPOINTS } from '../../constans/constans';`
```
      <Avatar
        alt="avatar"
        src={urlImg?.[0] === '/' ? ENDPOINTS.RESOURCES + urlImg : urlImg}
      ></Avatar>
```

2022-11-27 15:24 UTC, AndreyTsvetkov requested changes

2022-11-27 15:24 UTC, AndreyTsvetkov commented on src/components/GameItem/GameItem.tsx
> +import {useAddPlayerToLeaderboardMutation} from '../../services/leaderboard';
форматирование

2022-11-27 15:24 UTC, AndreyTsvetkov commented on src/components/GameItem/GameItem.tsx
> +      document.addEventListener('keydown', function keydownEvent(event){
зачем ушли от стрелок? так длинее и многословнее

2022-11-27 15:24 UTC, AndreyTsvetkov commented on src/components/GameItem/GameItem.tsx
> +        {/*Ваш текущий рекорд: <strong>{maxScore}</strong>*/}
? больше не  выводим счет?

2022-11-28 08:56 UTC, KaznacheevDaniil commented on src/components/LeaderboardItem/LeaderboardItem.tsx
> +      <Avatar alt="avatar" src={urlImg?.[0] === '/' ? 'https://ya-praktikum.tech/api/v2/resources' + urlImg : urlImg}></Avatar>
Сделано

2022-11-28 09:18 UTC, KaznacheevDaniil commented on src/components/GameItem/GameItem.tsx
> +        {/*Ваш текущий рекорд: <strong>{maxScore}</strong>*/}
Я решил от этой идеи отказаться, так как нет времени пилить под неё ручку

2022-11-28 09:18 UTC, KaznacheevDaniil commented on src/components/GameItem/GameItem.tsx
> +      document.addEventListener('keydown', function keydownEvent(event){
Вернул. Был эксперимент

2022-11-28 09:19 UTC, KaznacheevDaniil commented on src/components/GameItem/GameItem.tsx
> +import {useAddPlayerToLeaderboardMutation} from '../../services/leaderboard';
Сделано

2022-11-28 09:49 UTC, merged