Task 6 game init
MashaRakitskaya/PraktikumGameDoodleJump pull request #9
Opened 2022-09-06 15:10 UTC by KaznacheevDaniil

2022-09-12 13:17 UTC, MashaRakitskaya requested changes

2022-09-12 13:17 UTC, MashaRakitskaya commented on src/components/GameItem/GameItem.tsx
> +      setInterval(() => {
```
componentWillUnmount() {
   clearInterval(this.intervalId);
}    
```  
вроде ж нужно очистить еще  setInterval

2022-09-12 13:17 UTC, MashaRakitskaya commented on src/components/GameItem/GameItem.styles.js
> +  background: #fff;
вынеси background: #fff; в variables.css , думаю лучше все цвета хранить в одном месте для легкого управления ими

2022-09-14 06:21 UTC, AndreyTsvetkov requested changes
Написал немного комментов, + поддерживаю то, что Мария написала

2022-09-14 06:21 UTC, AndreyTsvetkov commented on src/components/GameItem/Character/Character.ts
> +  draw() {
я бы рекомендовал *всегда* использовать стрелочные функции в TypeScript, кроме случаев, когда есть явная и откомментированная в коде причина, почему решено использовать function (0.01% случаев, какие-нибудь хитрые оптимизации, где мы экономим каплю на передаче this) 

управление this слишком неявная вещь, и кусает за ногу регулярно, так что по умолчанию считаем function запрещенной

2022-09-14 06:21 UTC, AndreyTsvetkov commented on src/components/GameItem/Character/Character.ts
> +  ref: any; // локальный контекст канваса для отрисовки
тип канваса вполне себе известен, зачем any?
то же и про результат setInterval

2022-09-14 06:21 UTC, AndreyTsvetkov commented on src/components/GameItem/Character/Character.ts
> +  jump(platforms: any[]) {
платформа - воообще наш тип, тоже any не оправдан

2022-09-14 06:21 UTC, AndreyTsvetkov commented on src/components/GameItem/GameItem.tsx
> +    let platformCount = 20; // Общее оличество платформ на сцену
опечаточка

2022-09-14 06:21 UTC, AndreyTsvetkov commented on src/components/GameItem/GameItem.tsx
> +      platforms = createPlatforms(context, platformCount, platforms);
тут что-то не так. зачем platforms передается в метод, который должен породить платформы? внутри она модифицируется, а потом результат в нее же присваивается. это не очень интуитивное API, надо либо уж называть метод типа как fill(platforms), передавать туда коллекцию и пусть он ее заполняет, либо platforms = create(), и тогда пусть возвращает новую

2022-09-14 06:21 UTC, AndreyTsvetkov commented on src/components/GameItem/GameItem.tsx
> +        platforms[1].bottom - 60,
1) обращаемся по индексу - либо нужна проверка, либо комментарий, почему не нужна
2) 60 40 вынести в константы

2022-09-16 14:45 UTC, KaznacheevDaniil commented on src/pages/Game/Game.styles.js
> +export const Game = styled.div`
Убрал

2022-09-16 15:26 UTC, KaznacheevDaniil commented on src/components/GameItem/Platform/Platform.ts
> +      (platform: {
Упростил

2022-09-16 15:26 UTC, KaznacheevDaniil commented on src/components/GameItem/Platform/Platform.ts
> +  if (Character.posY < context.canvas.height / 3) {
Описал

2022-09-16 15:27 UTC, KaznacheevDaniil commented on src/components/GameItem/Platform/Platform.ts
> +    this.width = widthPlatform || 120;
Описал

2022-09-16 15:30 UTC, KaznacheevDaniil commented on src/components/GameItem/Character/Character.ts
> +    this.ref.fillStyle = 'rgb(0, 0, 0)';
Это заглушка, т.к. в будущем будут использоваться картинки

2022-09-16 15:33 UTC, KaznacheevDaniil commented on src/components/GameItem/GameItem.styles.js
> +  background: #fff;
Это заглушка при разработке. В будущем, поменяю на картинку

2022-09-16 15:45 UTC, KaznacheevDaniil commented on src/components/GameItem/GameItem.tsx
> +    let platformCount = 20; // Общее оличество платформ на сцену
Попрвил

2022-09-16 15:45 UTC, KaznacheevDaniil commented on src/components/GameItem/Character/Character.ts
> +  draw() {
Сделано

2022-09-16 15:51 UTC, KaznacheevDaniil commented on src/components/GameItem/GameItem.tsx
> +      setInterval(() => {
Сделано

2022-09-16 15:52 UTC, KaznacheevDaniil commented on src/components/GameItem/Character/Character.ts
> +        this.posY + this.height >= platform.bottom - 10 &&
Подписал комментарии. Это еще бэта версия условий. В окончательном варианте все распишу

2022-09-16 15:52 UTC, KaznacheevDaniil commented on src/components/GameItem/Character/Character.ts
> +    }, this.speedGame + 15);
Сделал

2022-09-16 15:58 UTC, KaznacheevDaniil commented on src/components/GameItem/Character/Character.ts
> +  jump(platforms: any[]) {
Поправлено

2022-09-16 15:58 UTC, KaznacheevDaniil commented on src/components/GameItem/Character/Character.ts
> +  ref: any; // локальный контекст канваса для отрисовки
Сделано

2022-09-16 15:59 UTC, KaznacheevDaniil commented on src/components/GameItem/GameItem.tsx
> +      platforms = createPlatforms(context, platformCount, platforms);
Поправил

2022-09-16 16:02 UTC, KaznacheevDaniil commented on src/components/GameItem/GameItem.tsx
> +        platforms[1].bottom - 60,
Сделано

2022-09-16 16:29 UTC, MashaRakitskaya commented on src/pages/Game/Game.styles.js
> +export const Game = styled.div`
ок

2022-09-16 16:34 UTC, MashaRakitskaya commented on src/components/GameItem/Platform/Platform.ts
> +    this.width = widthPlatform || 120;
ок

2022-09-16 16:35 UTC, MashaRakitskaya commented on src/components/GameItem/Platform/Platform.ts
> +  if (Character.posY < context.canvas.height / 3) {
ок

2022-09-16 16:39 UTC, MashaRakitskaya commented on src/components/GameItem/Platform/Platform.ts
> +      (platform: {
ок

2022-09-16 16:40 UTC, MashaRakitskaya commented on src/components/GameItem/Character/Character.ts
> +    this.ref.fillStyle = 'rgb(0, 0, 0)';
ок

2022-09-16 16:41 UTC, MashaRakitskaya commented on src/components/GameItem/Character/Character.ts
> +    }, this.speedGame + 15);
ок

2022-09-16 16:42 UTC, MashaRakitskaya commented on src/components/GameItem/Character/Character.ts
> +        this.posY + this.height >= platform.bottom - 10 &&
ок

2022-09-16 16:53 UTC, MashaRakitskaya commented on src/components/GameItem/GameItem.styles.js
> +  background: #fff;
Ок

2022-09-16 18:48 UTC, MashaRakitskaya commented on src/components/GameItem/GameItem.tsx
> +      setInterval(() => {
ок

2022-09-16 18:49 UTC, MashaRakitskaya commented on src/components/GameItem/Platform/Platform.ts
> +    this.width = widthPlatform || 120;
ок

2022-09-16 18:49 UTC, MashaRakitskaya commented on src/components/GameItem/Platform/Platform.ts
> +  if (Character.posY < context.canvas.height / 3) {
ок

2022-09-16 18:50 UTC, MashaRakitskaya commented on src/components/GameItem/Platform/Platform.ts
> +  return 0;
ок

2022-09-20 14:30 UTC, merged